using UnityEngine;
using TMPro;

public class ScoreManager : MonoBehaviour
{
    public TextMeshProUGUI textoPuntuacion; // Referencia al componente TextMeshProUGUI
    private PlayerControler jugador; // Referencia al script del jugador

    void Start()
    {
        jugador = FindObjectOfType<PlayerControler>(); // Encuentra el objeto del jugador
        ActualizarPuntuacion(); // Muestra la puntuaci贸n inicial
    }

    void Update()
    {
        // Actualiza la puntuaci贸n cada vez que cambia
        ActualizarPuntuacion();
    }

    private void ActualizarPuntuacion()
    {
        if (jugador != null)
        {
            textoPuntuacion.text = "Puntuaci贸n: " + jugador.Puntuacion.ToString(); // Actualiza el texto con la puntuaci贸n actual
        }
    }
}